version: '3.8'

services:
  llm_service:
    build:
      context: ./llm_service
    ports:
      - "8000:8000"
    volumes:
      - ./llm_service:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    depends_on:
      - llm_service
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend